INSERT [dbo].[Table1] ([Key], [TableId]) VALUES (1, 11)
INSERT [dbo].[Table1] ([Key], [TableId]) VALUES (2, 22)
INSERT [dbo].[Table1] ([Key], [TableId]) VALUES (4, 44)
INSERT [dbo].[Table1] ([Key], [TableId]) VALUES (5, 55)
INSERT [dbo].[Table1] ([Key], [TableId]) VALUES (6, 99)
