SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[Table1] (
		[Key]         [int] NOT NULL,
		[TableId]     [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Table1]
	ADD
	CONSTRAINT [PK_Table1]
	PRIMARY KEY
	CLUSTERED
	([Key])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[Table1] SET (LOCK_ESCALATION = TABLE)
GO
