SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[Table1] (
		[TableId]     [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Table1] SET (LOCK_ESCALATION = TABLE)
GO
